server:
  port: 8080

spring:
  application:
    name: cloudservice

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/streaming
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  cloud:
    aws:
      region:
        static: ap-southeast-1

      credentials:
        access-key: test
        secret-key: test

      s3:
        endpoint: http://localhost:4566
        region: ap-southeast-1
        path-style-access-enabled: true

      bucket:
        sales:
          name: sales-info
        process:
          name: process-image

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html