server:
  port: 8080

spring:
  application:
    name: cloudservice

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  datasource:
    url: jdbc:postgresql://localhost:5432/streaming
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      region:
        static: ap-southeast-1

      credentials:
        access-key: test
        secret-key: test

      s3:
        endpoint: http://localhost:4566
        region: ap-southeast-1
        path-style-access-enabled: true
        presigned-url-expiry: 86400

      bucket:
        sales:
          name: sales-info
        process:
          name: process-s3-migration
        streaming:
          name: streaming

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger-ui.html

# FFmpeg configuration
ffmpeg:
  path: ${FFMPEG_PATH:C:/ffmpeg/bin/ffmpeg.exe}